export const cardsSeedData = [
  // ========================================
  // LEGENDARY (2 cards - 7%)
  // High stats across the board, game-changing cards
  // ========================================
  {
    name: 'Dragón Ancestral',
    power: 95,
    speed: 78,
    intelligence: 82,
    defense: 90,
    agility: 75,
    description:
      'Rey de los dragones con poder inigualable y sabiduría milenaria',
    rarity: 'legendary',
  },
  {
    name: 'Cyborg Asesino',
    power: 88,
    speed: 92,
    intelligence: 90,
    defense: 80,
    agility: 85,
    description: 'Fusión perfecta de hombre y máquina, asesino implacable',
    rarity: 'legendary',
  },

  // ========================================
  // EPIC (6 cards - 20%)
  // Strong specializations with 2-3 high stats
  // ========================================
  {
    name: 'Ninja Sombrío',
    power: 65,
    speed: 95,
    intelligence: 78,
    defense: 45,
    agility: 98,
    description: 'Maestro del sigilo con velocidad y agilidad sobrehumanas',
    rarity: 'epic',
  },
  {
    name: 'Archimago',
    power: 70,
    speed: 50,
    intelligence: 98,
    defense: 60,
    agility: 48,
    description: 'Guardián supremo del conocimiento arcano y hechizos antiguos',
    rarity: 'epic',
  },
  {
    name: 'Titán de Acero',
    power: 90,
    speed: 35,
    intelligence: 55,
    defense: 96,
    agility: 30,
    description: 'Coloso indestructible forjado en metal viviente',
    rarity: 'epic',
  },
  {
    name: 'Bestia Primordial',
    power: 92,
    speed: 88,
    intelligence: 45,
    defense: 72,
    agility: 90,
    description: 'Criatura ancestral con instintos depredadores letales',
    rarity: 'epic',
  },
  {
    name: 'Telépata Supremo',
    power: 50,
    speed: 60,
    intelligence: 96,
    defense: 58,
    agility: 65,
    description: 'Maestro de la mente capaz de controlar pensamientos',
    rarity: 'epic',
  },
  {
    name: 'Ángel Guardián',
    power: 82,
    speed: 75,
    intelligence: 85,
    defense: 88,
    agility: 78,
    description: 'Protector celestial con poder divino equilibrado',
    rarity: 'epic',
  },

  // ========================================
  // RARE (10 cards - 33%)
  // Clear specialization in 1-2 stats
  // ========================================
  {
    name: 'Paladín Sagrado',
    power: 78,
    speed: 60,
    intelligence: 68,
    defense: 85,
    agility: 55,
    description: 'Guerrero santo con armadura bendecida y fe inquebrantable',
    rarity: 'rare',
  },
  {
    name: 'Asesino de Sombras',
    power: 65,
    speed: 90,
    intelligence: 75,
    defense: 42,
    agility: 92,
    description: 'Maestro de las sombras que elimina sin ser visto',
    rarity: 'rare',
  },
  {
    name: 'Hechicera Elemental',
    power: 72,
    speed: 58,
    intelligence: 88,
    defense: 55,
    agility: 62,
    description: 'Maestra de los elementos: fuego, agua, tierra y aire',
    rarity: 'rare',
  },
  {
    name: 'Gladiador Campeón',
    power: 85,
    speed: 70,
    intelligence: 50,
    defense: 75,
    agility: 65,
    description: 'Guerrero invicto del coliseo con múltiples victorias',
    rarity: 'rare',
  },
  {
    name: 'Arquero Maestro',
    power: 60,
    speed: 82,
    intelligence: 72,
    defense: 48,
    agility: 88,
    description: 'Tirador legendario con puntería perfecta a larga distancia',
    rarity: 'rare',
  },
  {
    name: 'Golem de Roca',
    power: 80,
    speed: 32,
    intelligence: 40,
    defense: 92,
    agility: 28,
    description: 'Guardián de piedra antigua prácticamente indestructible',
    rarity: 'rare',
  },
  {
    name: 'Piromante',
    power: 88,
    speed: 62,
    intelligence: 80,
    defense: 50,
    agility: 58,
    description: 'Maestro del fuego capaz de invocar llamas devastadoras',
    rarity: 'rare',
  },
  {
    name: 'Acróbata Letal',
    power: 55,
    speed: 85,
    intelligence: 68,
    defense: 45,
    agility: 95,
    description: 'Artista circense convertido en combatiente ágil mortal',
    rarity: 'rare',
  },
  {
    name: 'Druida Ancestral',
    power: 65,
    speed: 58,
    intelligence: 85,
    defense: 70,
    agility: 60,
    description: 'Guardián de la naturaleza con conexión a la tierra',
    rarity: 'rare',
  },
  {
    name: 'Samurái Errante',
    power: 75,
    speed: 75,
    intelligence: 70,
    defense: 72,
    agility: 78,
    description: 'Guerrero honorable con perfecto equilibrio en combate',
    rarity: 'rare',
  },

  // ========================================
  // COMMON (12 cards - 40%)
  // Balanced stats, no extreme specializations
  // ========================================
  {
    name: 'Soldado de Elite',
    power: 65,
    speed: 68,
    intelligence: 62,
    defense: 70,
    agility: 65,
    description: 'Militar entrenado con experiencia en combate táctico',
    rarity: 'common',
  },
  {
    name: 'Explorador Veterano',
    power: 58,
    speed: 72,
    intelligence: 68,
    defense: 55,
    agility: 75,
    description: 'Rastreador experto que conoce el terreno como nadie',
    rarity: 'common',
  },
  {
    name: 'Guardián del Templo',
    power: 70,
    speed: 55,
    intelligence: 60,
    defense: 75,
    agility: 52,
    description: 'Protector dedicado de lugares sagrados',
    rarity: 'common',
  },
  {
    name: 'Mago Aprendiz',
    power: 48,
    speed: 52,
    intelligence: 75,
    defense: 50,
    agility: 55,
    description: 'Estudiante de las artes arcanas en desarrollo',
    rarity: 'common',
  },
  {
    name: 'Mercenario Experimentado',
    power: 68,
    speed: 70,
    intelligence: 62,
    defense: 62,
    agility: 68,
    description: 'Guerrero a sueldo con múltiples batallas ganadas',
    rarity: 'common',
  },
  {
    name: 'Cazador Tribal',
    power: 62,
    speed: 75,
    intelligence: 58,
    defense: 55,
    agility: 72,
    description: 'Cazador hábil de la tribu con reflejos agudos',
    rarity: 'common',
  },
  {
    name: 'Ingeniero de Batalla',
    power: 55,
    speed: 58,
    intelligence: 78,
    defense: 65,
    agility: 60,
    description: 'Estratega técnico especializado en maquinaria bélica',
    rarity: 'common',
  },
  {
    name: 'Duelista Noble',
    power: 70,
    speed: 68,
    intelligence: 65,
    defense: 62,
    agility: 70,
    description: 'Espadachín aristocrático con estilo refinado',
    rarity: 'common',
  },
  {
    name: 'Monje Guerrero',
    power: 65,
    speed: 70,
    intelligence: 72,
    defense: 60,
    agility: 75,
    description: 'Luchador disciplinado que combina mente y cuerpo',
    rarity: 'common',
  },
  {
    name: 'Pistolero del Oeste',
    power: 62,
    speed: 78,
    intelligence: 60,
    defense: 48,
    agility: 75,
    description: 'Tirador rápido legendario de la frontera',
    rarity: 'common',
  },
  {
    name: 'Alquimista Viajero',
    power: 52,
    speed: 55,
    intelligence: 80,
    defense: 50,
    agility: 58,
    description: 'Científico místico experto en pociones y experimentos',
    rarity: 'common',
  },
  {
    name: 'Bárbaro Norteño',
    power: 78,
    speed: 62,
    intelligence: 48,
    defense: 70,
    agility: 60,
    description: 'Guerrero tribal de las tierras heladas del norte',
    rarity: 'common',
  },
  {
    name: 'Berserker Vikingo',
    power: 80,
    speed: 65,
    intelligence: 45,
    defense: 68,
    agility: 58,
    description: 'Guerrero furioso que pelea sin miedo ni control',
    rarity: 'common',
  },
  {
    name: 'Clérigo Sanador',
    power: 50,
    speed: 55,
    intelligence: 72,
    defense: 65,
    agility: 58,
    description: 'Sacerdote dedicado a curar heridas y proteger aliados',
    rarity: 'common',
  },

  // ========================================
  // LEGENDARY ADICIONALES (3 cards más - total 5)
  // ========================================
  {
    name: 'Fénix Inmortal',
    power: 85,
    speed: 92,
    intelligence: 88,
    defense: 82,
    agility: 90,
    description: 'Ave legendaria que renace de sus cenizas con poder renovado',
    rarity: 'legendary',
  },
  {
    name: 'Demonio Primigenio',
    power: 98,
    speed: 80,
    intelligence: 85,
    defense: 88,
    agility: 78,
    description: 'Entidad oscura de poder ancestral y destrucción absoluta',
    rarity: 'legendary',
  },
  {
    name: 'Maestro del Tiempo',
    power: 75,
    speed: 95,
    intelligence: 98,
    defense: 80,
    agility: 88,
    description: 'Manipulador del espacio-tiempo con control sobre la realidad',
    rarity: 'legendary',
  },

  // ========================================
  // EPIC ADICIONALES (8 cards más - total 14)
  // ========================================
  {
    name: 'Valquiria de Guerra',
    power: 82,
    speed: 88,
    intelligence: 75,
    defense: 78,
    agility: 85,
    description: 'Guerrera celestial que escoge a los héroes caídos',
    rarity: 'epic',
  },
  {
    name: 'Nigromante Oscuro',
    power: 68,
    speed: 55,
    intelligence: 94,
    defense: 62,
    agility: 52,
    description: 'Maestro de la muerte capaz de invocar ejércitos no-muertos',
    rarity: 'epic',
  },
  {
    name: 'Hydra de Tres Cabezas',
    power: 90,
    speed: 65,
    intelligence: 50,
    defense: 92,
    agility: 60,
    description: 'Bestia mitológica con regeneración imparable',
    rarity: 'epic',
  },
  {
    name: 'Espadachín Espectral',
    power: 75,
    speed: 95,
    intelligence: 70,
    defense: 48,
    agility: 98,
    description: 'Fantasma guerrero con velocidad sobrenatural',
    rarity: 'epic',
  },
  {
    name: 'Kraken Abismal',
    power: 95,
    speed: 70,
    intelligence: 65,
    defense: 90,
    agility: 68,
    description: 'Monstruo marino colosal con tentáculos destructivos',
    rarity: 'epic',
  },
  {
    name: 'Invocador Supremo',
    power: 60,
    speed: 58,
    intelligence: 96,
    defense: 65,
    agility: 62,
    description: 'Mago capaz de convocar criaturas de otros planos',
    rarity: 'epic',
  },
  {
    name: 'Centinela Automatizado',
    power: 85,
    speed: 78,
    intelligence: 82,
    defense: 94,
    agility: 70,
    description: 'Robot de guerra con sistemas defensivos avanzados',
    rarity: 'epic',
  },
  {
    name: 'Lobo Alfa Gigante',
    power: 82,
    speed: 92,
    intelligence: 68,
    defense: 72,
    agility: 94,
    description: 'Líder de la manada con instintos cazadores letales',
    rarity: 'epic',
  },

  // ========================================
  // RARE ADICIONALES (14 cards más - total 24)
  // ========================================
  {
    name: 'Caballero Negro',
    power: 80,
    speed: 68,
    intelligence: 65,
    defense: 88,
    agility: 62,
    description: 'Guerrero misterioso con armadura maldita impenetrable',
    rarity: 'rare',
  },
  {
    name: 'Brujo del Pantano',
    power: 65,
    speed: 52,
    intelligence: 86,
    defense: 60,
    agility: 58,
    description: 'Hechicero oscuro que domina las artes prohibidas',
    rarity: 'rare',
  },
  {
    name: 'Lancero Dragón',
    power: 78,
    speed: 75,
    intelligence: 62,
    defense: 70,
    agility: 72,
    description: 'Guerrero montado en dragón con lanza legendaria',
    rarity: 'rare',
  },
  {
    name: 'Ilusionista Maestro',
    power: 52,
    speed: 72,
    intelligence: 90,
    defense: 48,
    agility: 78,
    description: 'Mago especializado en engaños y trucos visuales',
    rarity: 'rare',
  },
  {
    name: 'Chamán Espiritual',
    power: 60,
    speed: 62,
    intelligence: 84,
    defense: 68,
    agility: 65,
    description: 'Médico tribal con conexión a los espíritus ancestrales',
    rarity: 'rare',
  },
  {
    name: 'Corsario Legendario',
    power: 72,
    speed: 82,
    intelligence: 70,
    defense: 58,
    agility: 85,
    description: 'Pirata temido de los siete mares con astucia mortal',
    rarity: 'rare',
  },
  {
    name: 'Gólem de Cristal',
    power: 75,
    speed: 40,
    intelligence: 55,
    defense: 95,
    agility: 35,
    description: 'Guardián cristalino prácticamente invulnerable',
    rarity: 'rare',
  },
  {
    name: 'Francotirador Elite',
    power: 62,
    speed: 70,
    intelligence: 80,
    defense: 52,
    agility: 75,
    description: 'Tirador de precisión con mira milimétrica',
    rarity: 'rare',
  },
  {
    name: 'Caballero del Alba',
    power: 78,
    speed: 72,
    intelligence: 68,
    defense: 82,
    agility: 70,
    description: 'Protector de la luz con espada sagrada',
    rarity: 'rare',
  },
  {
    name: 'Elementalista de Hielo',
    power: 70,
    speed: 65,
    intelligence: 88,
    defense: 62,
    agility: 68,
    description: 'Mago glacial capaz de congelar enemigos al instante',
    rarity: 'rare',
  },
  {
    name: 'Guardián del Bosque',
    power: 68,
    speed: 70,
    intelligence: 75,
    defense: 78,
    agility: 72,
    description: 'Protector natural con dominio sobre plantas y animales',
    rarity: 'rare',
  },
  {
    name: 'Espadachín Dual',
    power: 72,
    speed: 85,
    intelligence: 65,
    defense: 58,
    agility: 88,
    description: 'Maestro de dos espadas con ataques vertiginosos',
    rarity: 'rare',
  },
  {
    name: 'Oráculo Vidente',
    power: 48,
    speed: 55,
    intelligence: 92,
    defense: 60,
    agility: 62,
    description: 'Profeta capaz de ver el futuro y predecir destinos',
    rarity: 'rare',
  },
  {
    name: 'Minotauro de Guerra',
    power: 88,
    speed: 65,
    intelligence: 48,
    defense: 80,
    agility: 62,
    description: 'Bestia-hombre con fuerza bruta devastadora',
    rarity: 'rare',
  },

  // ========================================
  // COMMON ADICIONALES (19 cards más - total 29)
  // ========================================
  {
    name: 'Espadachín Novato',
    power: 60,
    speed: 65,
    intelligence: 58,
    defense: 60,
    agility: 68,
    description: 'Guerrero en entrenamiento con técnica básica',
    rarity: 'common',
  },
  {
    name: 'Ladrón de Ciudad',
    power: 52,
    speed: 78,
    intelligence: 68,
    defense: 45,
    agility: 80,
    description: 'Criminal ágil experto en robo y evasión',
    rarity: 'common',
  },
  {
    name: 'Arquera del Bosque',
    power: 55,
    speed: 72,
    intelligence: 65,
    defense: 50,
    agility: 75,
    description: 'Cazadora con arco experta en combate a distancia',
    rarity: 'common',
  },
  {
    name: 'Forjador Enano',
    power: 70,
    speed: 48,
    intelligence: 75,
    defense: 78,
    agility: 50,
    description: 'Herrero maestro con fuerza y conocimiento técnico',
    rarity: 'common',
  },
  {
    name: 'Místico Encapuchado',
    power: 50,
    speed: 58,
    intelligence: 78,
    defense: 55,
    agility: 62,
    description: 'Mago errante con conocimientos arcanos limitados',
    rarity: 'common',
  },
  {
    name: 'Cazador de Recompensas',
    power: 68,
    speed: 72,
    intelligence: 65,
    defense: 58,
    agility: 70,
    description: 'Rastreador profesional especializado en capturar fugitivos',
    rarity: 'common',
  },
  {
    name: 'Guerrero Tribal',
    power: 72,
    speed: 68,
    intelligence: 52,
    defense: 65,
    agility: 68,
    description: 'Combatiente de tribu con tácticas ancestrales',
    rarity: 'common',
  },
  {
    name: 'Médico de Campo',
    power: 48,
    speed: 60,
    intelligence: 75,
    defense: 58,
    agility: 60,
    description: 'Sanador de guerra especializado en primeros auxilios',
    rarity: 'common',
  },
  {
    name: 'Explorador del Desierto',
    power: 58,
    speed: 75,
    intelligence: 70,
    defense: 52,
    agility: 78,
    description: 'Guía nómada experto en supervivencia extrema',
    rarity: 'common',
  },
  {
    name: 'Escudero Fiel',
    power: 65,
    speed: 62,
    intelligence: 60,
    defense: 72,
    agility: 62,
    description: 'Aprendiz de caballero con lealtad inquebrantable',
    rarity: 'common',
  },
  {
    name: 'Juglar Combatiente',
    power: 55,
    speed: 70,
    intelligence: 68,
    defense: 50,
    agility: 75,
    description: 'Artista callejero que usa acrobacia en combate',
    rarity: 'common',
  },
  {
    name: 'Pescador de Mar Profundo',
    power: 68,
    speed: 62,
    intelligence: 65,
    defense: 70,
    agility: 60,
    description: 'Marinero resistente acostumbrado a las tormentas',
    rarity: 'common',
  },
  {
    name: 'Minero de Montaña',
    power: 75,
    speed: 52,
    intelligence: 60,
    defense: 75,
    agility: 50,
    description: 'Trabajador fuerte y resistente de las minas',
    rarity: 'common',
  },
  {
    name: 'Acólito del Templo',
    power: 50,
    speed: 58,
    intelligence: 72,
    defense: 62,
    agility: 60,
    description: 'Estudiante religioso en formación espiritual',
    rarity: 'common',
  },
  {
    name: 'Guardabosques',
    power: 62,
    speed: 70,
    intelligence: 68,
    defense: 58,
    agility: 72,
    description: 'Protector del bosque con conocimiento natural',
    rarity: 'common',
  },
  {
    name: 'Luchador de Arena',
    power: 72,
    speed: 68,
    intelligence: 55,
    defense: 68,
    agility: 65,
    description: 'Gladiador experimentado en combate cuerpo a cuerpo',
    rarity: 'common',
  },
  {
    name: 'Inventor Excéntrico',
    power: 52,
    speed: 60,
    intelligence: 80,
    defense: 55,
    agility: 58,
    description: 'Científico creativo con artefactos experimentales',
    rarity: 'common',
  },
  {
    name: 'Domador de Bestias',
    power: 60,
    speed: 65,
    intelligence: 70,
    defense: 62,
    agility: 68,
    description: 'Entrenador animal con control sobre criaturas salvajes',
    rarity: 'common',
  },
  {
    name: 'Vigilante Nocturno',
    power: 62,
    speed: 70,
    intelligence: 65,
    defense: 65,
    agility: 72,
    description: 'Guardián de la ciudad experto en patrullaje urbano',
    rarity: 'common',
  },
];
