export const cardsSeedData = [
  // ========================================
  // LEGENDARY (2 cards - 7%)
  // High stats across the board, game-changing cards
  // ========================================
  {
    name: 'Dragón Ancestral',
    power: 95,
    speed: 78,
    intelligence: 82,
    defense: 90,
    agility: 75,
    description: 'Rey de los dragones con poder inigualable y sabiduría milenaria',
    rarity: 'legendary',
  },
  {
    name: 'Cyborg Asesino',
    power: 88,
    speed: 92,
    intelligence: 90,
    defense: 80,
    agility: 85,
    description: 'Fusión perfecta de hombre y máquina, asesino implacable',
    rarity: 'legendary',
  },

  // ========================================
  // EPIC (6 cards - 20%)
  // Strong specializations with 2-3 high stats
  // ========================================
  {
    name: 'Ninja Sombrío',
    power: 65,
    speed: 95,
    intelligence: 78,
    defense: 45,
    agility: 98,
    description: 'Maestro del sigilo con velocidad y agilidad sobrehumanas',
    rarity: 'epic',
  },
  {
    name: 'Archimago',
    power: 70,
    speed: 50,
    intelligence: 98,
    defense: 60,
    agility: 48,
    description: 'Guardián supremo del conocimiento arcano y hechizos antiguos',
    rarity: 'epic',
  },
  {
    name: 'Titán de Acero',
    power: 90,
    speed: 35,
    intelligence: 55,
    defense: 96,
    agility: 30,
    description: 'Coloso indestructible forjado en metal viviente',
    rarity: 'epic',
  },
  {
    name: 'Bestia Primordial',
    power: 92,
    speed: 88,
    intelligence: 45,
    defense: 72,
    agility: 90,
    description: 'Criatura ancestral con instintos depredadores letales',
    rarity: 'epic',
  },
  {
    name: 'Telépata Supremo',
    power: 50,
    speed: 60,
    intelligence: 96,
    defense: 58,
    agility: 65,
    description: 'Maestro de la mente capaz de controlar pensamientos',
    rarity: 'epic',
  },
  {
    name: 'Ángel Guardián',
    power: 82,
    speed: 75,
    intelligence: 85,
    defense: 88,
    agility: 78,
    description: 'Protector celestial con poder divino equilibrado',
    rarity: 'epic',
  },

  // ========================================
  // RARE (10 cards - 33%)
  // Clear specialization in 1-2 stats
  // ========================================
  {
    name: 'Paladín Sagrado',
    power: 78,
    speed: 60,
    intelligence: 68,
    defense: 85,
    agility: 55,
    description: 'Guerrero santo con armadura bendecida y fe inquebrantable',
    rarity: 'rare',
  },
  {
    name: 'Asesino de Sombras',
    power: 65,
    speed: 90,
    intelligence: 75,
    defense: 42,
    agility: 92,
    description: 'Maestro de las sombras que elimina sin ser visto',
    rarity: 'rare',
  },
  {
    name: 'Hechicera Elemental',
    power: 72,
    speed: 58,
    intelligence: 88,
    defense: 55,
    agility: 62,
    description: 'Maestra de los elementos: fuego, agua, tierra y aire',
    rarity: 'rare',
  },
  {
    name: 'Gladiador Campeón',
    power: 85,
    speed: 70,
    intelligence: 50,
    defense: 75,
    agility: 65,
    description: 'Guerrero invicto del coliseo con múltiples victorias',
    rarity: 'rare',
  },
  {
    name: 'Arquero Maestro',
    power: 60,
    speed: 82,
    intelligence: 72,
    defense: 48,
    agility: 88,
    description: 'Tirador legendario con puntería perfecta a larga distancia',
    rarity: 'rare',
  },
  {
    name: 'Golem de Roca',
    power: 80,
    speed: 32,
    intelligence: 40,
    defense: 92,
    agility: 28,
    description: 'Guardián de piedra antigua prácticamente indestructible',
    rarity: 'rare',
  },
  {
    name: 'Piromante',
    power: 88,
    speed: 62,
    intelligence: 80,
    defense: 50,
    agility: 58,
    description: 'Maestro del fuego capaz de invocar llamas devastadoras',
    rarity: 'rare',
  },
  {
    name: 'Acróbata Letal',
    power: 55,
    speed: 85,
    intelligence: 68,
    defense: 45,
    agility: 95,
    description: 'Artista circense convertido en combatiente ágil mortal',
    rarity: 'rare',
  },
  {
    name: 'Druida Ancestral',
    power: 65,
    speed: 58,
    intelligence: 85,
    defense: 70,
    agility: 60,
    description: 'Guardián de la naturaleza con conexión a la tierra',
    rarity: 'rare',
  },
  {
    name: 'Samurái Errante',
    power: 75,
    speed: 75,
    intelligence: 70,
    defense: 72,
    agility: 78,
    description: 'Guerrero honorable con perfecto equilibrio en combate',
    rarity: 'rare',
  },

  // ========================================
  // COMMON (12 cards - 40%)
  // Balanced stats, no extreme specializations
  // ========================================
  {
    name: 'Soldado de Elite',
    power: 65,
    speed: 68,
    intelligence: 62,
    defense: 70,
    agility: 65,
    description: 'Militar entrenado con experiencia en combate táctico',
    rarity: 'common',
  },
  {
    name: 'Explorador Veterano',
    power: 58,
    speed: 72,
    intelligence: 68,
    defense: 55,
    agility: 75,
    description: 'Rastreador experto que conoce el terreno como nadie',
    rarity: 'common',
  },
  {
    name: 'Guardián del Templo',
    power: 70,
    speed: 55,
    intelligence: 60,
    defense: 75,
    agility: 52,
    description: 'Protector dedicado de lugares sagrados',
    rarity: 'common',
  },
  {
    name: 'Mago Aprendiz',
    power: 48,
    speed: 52,
    intelligence: 75,
    defense: 50,
    agility: 55,
    description: 'Estudiante de las artes arcanas en desarrollo',
    rarity: 'common',
  },
  {
    name: 'Mercenario Experimentado',
    power: 68,
    speed: 70,
    intelligence: 62,
    defense: 62,
    agility: 68,
    description: 'Guerrero a sueldo con múltiples batallas ganadas',
    rarity: 'common',
  },
  {
    name: 'Cazador Tribal',
    power: 62,
    speed: 75,
    intelligence: 58,
    defense: 55,
    agility: 72,
    description: 'Cazador hábil de la tribu con reflejos agudos',
    rarity: 'common',
  },
  {
    name: 'Ingeniero de Batalla',
    power: 55,
    speed: 58,
    intelligence: 78,
    defense: 65,
    agility: 60,
    description: 'Estratega técnico especializado en maquinaria bélica',
    rarity: 'common',
  },
  {
    name: 'Duelista Noble',
    power: 70,
    speed: 68,
    intelligence: 65,
    defense: 62,
    agility: 70,
    description: 'Espadachín aristocrático con estilo refinado',
    rarity: 'common',
  },
  {
    name: 'Monje Guerrero',
    power: 65,
    speed: 70,
    intelligence: 72,
    defense: 60,
    agility: 75,
    description: 'Luchador disciplinado que combina mente y cuerpo',
    rarity: 'common',
  },
  {
    name: 'Pistolero del Oeste',
    power: 62,
    speed: 78,
    intelligence: 60,
    defense: 48,
    agility: 75,
    description: 'Tirador rápido legendario de la frontera',
    rarity: 'common',
  },
  {
    name: 'Alquimista Viajero',
    power: 52,
    speed: 55,
    intelligence: 80,
    defense: 50,
    agility: 58,
    description: 'Científico místico experto en pociones y experimentos',
    rarity: 'common',
  },
  {
    name: 'Bárbaro Norteño',
    power: 78,
    speed: 62,
    intelligence: 48,
    defense: 70,
    agility: 60,
    description: 'Guerrero tribal de las tierras heladas del norte',
    rarity: 'common',
  },
];
