export const cardsSeedData = [
  {
    name: 'Dragón de Fuego',
    power: 95,
    speed: 70,
    intelligence: 60,
    defense: 85,
    agility: 65,
    description: 'Un poderoso dragón con aliento de fuego devastador',
    rarity: 'legendary',
  },
  {
    name: 'Ninja Veloz',
    power: 60,
    speed: 98,
    intelligence: 75,
    defense: 40,
    agility: 95,
    description: 'Maestro del sigilo y la velocidad sobrehumana',
    rarity: 'epic',
  },
  {
    name: 'Mago Sabio',
    power: 70,
    speed: 45,
    intelligence: 99,
    defense: 50,
    agility: 40,
    description: 'Guardián del conocimiento ancestral y la magia',
    rarity: 'epic',
  },
  {
    name: 'Guerrero Tanque',
    power: 80,
    speed: 40,
    intelligence: 50,
    defense: 99,
    agility: 35,
    description: 'Protector inquebrantable con armadura impenetrable',
    rarity: 'rare',
  },
  {
    name: 'Ladrón Ágil',
    power: 50,
    speed: 85,
    intelligence: 70,
    defense: 35,
    agility: 99,
    description: 'Maestro del arte del robo y la acrobacia',
    rarity: 'rare',
  },
  {
    name: 'Robot Titán',
    power: 90,
    speed: 55,
    intelligence: 80,
    defense: 95,
    agility: 50,
    description: 'Máquina de guerra con tecnología avanzada',
    rarity: 'legendary',
  },
  {
    name: 'Hechicera Oscura',
    power: 75,
    speed: 60,
    intelligence: 92,
    defense: 55,
    agility: 65,
    description: 'Maestra de las artes oscuras y los hechizos prohibidos',
    rarity: 'epic',
  },
  {
    name: 'Caballero Noble',
    power: 70,
    speed: 65,
    intelligence: 60,
    defense: 80,
    agility: 60,
    description: 'Defensor del reino con honor y valentía',
    rarity: 'rare',
  },
  {
    name: 'Arquero Élite',
    power: 55,
    speed: 80,
    intelligence: 75,
    defense: 45,
    agility: 85,
    description: 'Tirador experto con puntería perfecta',
    rarity: 'rare',
  },
  {
    name: 'Bestia Salvaje',
    power: 88,
    speed: 90,
    intelligence: 40,
    defense: 70,
    agility: 92,
    description: 'Criatura feroz con instintos depredadores',
    rarity: 'epic',
  },
  {
    name: 'Cyborg Asesino',
    power: 82,
    speed: 88,
    intelligence: 85,
    defense: 75,
    agility: 80,
    description: 'Fusión perfecta de hombre y máquina',
    rarity: 'legendary',
  },
  {
    name: 'Elemental de Hielo',
    power: 65,
    speed: 50,
    intelligence: 70,
    defense: 85,
    agility: 55,
    description: 'Ser místico con control sobre el hielo',
    rarity: 'rare',
  },
  {
    name: 'Samurái',
    power: 75,
    speed: 75,
    intelligence: 70,
    defense: 70,
    agility: 75,
    description: 'Guerrero equilibrado con honor bushido',
    rarity: 'epic',
  },
  {
    name: 'Asesino Silencioso',
    power: 60,
    speed: 92,
    intelligence: 80,
    defense: 40,
    agility: 95,
    description: 'Maestro de las sombras y el asesinato',
    rarity: 'rare',
  },
  {
    name: 'Titán de Piedra',
    power: 85,
    speed: 30,
    intelligence: 45,
    defense: 98,
    agility: 25,
    description: 'Golem indestructible de roca antigua',
    rarity: 'epic',
  },
  {
    name: 'Fénix',
    power: 70,
    speed: 88,
    intelligence: 75,
    defense: 60,
    agility: 85,
    description: 'Ave inmortal que renace de sus cenizas',
    rarity: 'legendary',
  },
  {
    name: 'Berserker',
    power: 95,
    speed: 70,
    intelligence: 40,
    defense: 65,
    agility: 60,
    description: 'Guerrero furioso con fuerza descomunal',
    rarity: 'rare',
  },
  {
    name: 'Telépata',
    power: 45,
    speed: 55,
    intelligence: 98,
    defense: 50,
    agility: 60,
    description: 'Maestro de la mente con poderes psíquicos',
    rarity: 'epic',
  },
  {
    name: 'Soldado Táctico',
    power: 65,
    speed: 70,
    intelligence: 85,
    defense: 70,
    agility: 75,
    description: 'Estratega militar con entrenamiento avanzado',
    rarity: 'common',
  },
  {
    name: 'Demonio',
    power: 92,
    speed: 75,
    intelligence: 80,
    defense: 70,
    agility: 78,
    description: 'Entidad infernal con poder sobrenatural',
    rarity: 'legendary',
  },
  {
    name: 'Guardián Celestial',
    power: 80,
    speed: 70,
    intelligence: 88,
    defense: 90,
    agility: 72,
    description: 'Protector divino de los cielos',
    rarity: 'legendary',
  },
  {
    name: 'Mercenario',
    power: 70,
    speed: 75,
    intelligence: 65,
    defense: 60,
    agility: 70,
    description: 'Guerrero a sueldo con experiencia en combate',
    rarity: 'common',
  },
  {
    name: 'Alquimista',
    power: 55,
    speed: 50,
    intelligence: 90,
    defense: 45,
    agility: 55,
    description: 'Maestro de pociones y transformaciones',
    rarity: 'rare',
  },
  {
    name: 'Pistolero',
    power: 65,
    speed: 85,
    intelligence: 70,
    defense: 50,
    agility: 80,
    description: 'Tirador rápido del viejo oeste',
    rarity: 'rare',
  },
  {
    name: 'Vampiro Ancestral',
    power: 78,
    speed: 82,
    intelligence: 85,
    defense: 75,
    agility: 80,
    description: 'Inmortal sediento de sangre con siglos de experiencia',
    rarity: 'legendary',
  },
];
